// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQB6LFLXDfzbGiY9AaChKZZ0ykLmbwVGg',
    appId: '1:675893502940:web:4dd164290e571beb6e6519',
    messagingSenderId: '675893502940',
    projectId: 'sicerdas-22060xx',
    authDomain: 'sicerdas-22060xx.firebaseapp.com',
    databaseURL: 'https://sicerdas-22060xx-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sicerdas-22060xx.firebasestorage.app',
    measurementId: 'G-707MSZCXL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0XLFeqHk-MclAQ7G5nqosflkP7WY2SWE',
    appId: '1:675893502940:android:46167dc37c57b9b16e6519',
    messagingSenderId: '675893502940',
    projectId: 'sicerdas-22060xx',
    databaseURL: 'https://sicerdas-22060xx-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sicerdas-22060xx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2NFPuGfNbYnPWCHkYZSK1Vjk-ck7T3sg',
    appId: '1:675893502940:ios:eae597711deb64d96e6519',
    messagingSenderId: '675893502940',
    projectId: 'sicerdas-22060xx',
    databaseURL: 'https://sicerdas-22060xx-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sicerdas-22060xx.firebasestorage.app',
    iosClientId: '675893502940-3345cbk30b49h08267kejev6fti4vmve.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectSicerdas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2NFPuGfNbYnPWCHkYZSK1Vjk-ck7T3sg',
    appId: '1:675893502940:ios:eae597711deb64d96e6519',
    messagingSenderId: '675893502940',
    projectId: 'sicerdas-22060xx',
    databaseURL: 'https://sicerdas-22060xx-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sicerdas-22060xx.firebasestorage.app',
    iosClientId: '675893502940-3345cbk30b49h08267kejev6fti4vmve.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectSicerdas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQB6LFLXDfzbGiY9AaChKZZ0ykLmbwVGg',
    appId: '1:675893502940:web:a4e68b7a5d91d6956e6519',
    messagingSenderId: '675893502940',
    projectId: 'sicerdas-22060xx',
    authDomain: 'sicerdas-22060xx.firebaseapp.com',
    databaseURL: 'https://sicerdas-22060xx-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sicerdas-22060xx.firebasestorage.app',
    measurementId: 'G-9S02S3KSSE',
  );
}
